name: lucky_routine
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  appsflyer_sdk: ^6.17.5
  app_tracking_transparency: ^2.0.6+1
  shared_preferences: ^2.5.3
  webview_flutter_wkwebview: ^3.23.1
  url_launcher: ^6.3.2
  external_app_launcher: ^4.0.3
  flutter_fortune_wheel: ^1.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
 
flutter_launcher_icons:
  ios: true
  image_path: "assets/images/icon.png"